#!/bin/bash
#Ejecutar cuando android esté conectado por USB al PC

#Enumerar todos los paquetes y sus archivos asociados
adb shell pm list packages | tail -n +2 | awk '{print substr($0,9, length($0) -0)}' > /dev/null 2>&1 >> a.txt
echo "Todos los paquetes 'com' han sido guardados en 'a.txt'"
